### ISSUE TITLE
Fix credits for Cognimates

### ISSUE THREAD

**Issue by stefania11** [touretzkyds/ai4k12#1]
I am the creator of Cognimates as it is my Master Thesis project and I have been working on it for the past 2 years. Cynthia is my advisor by not the creator of this project. Pasting bellow a corrected description for your wiki as I cannot do a PR on the wiki.. 

# Cognimates
* Name: Cognimates
* Subject Area: General AI
* Type: Web site with a variety of AI demo projects/activities powered by custom created Scratch extensions
* Grade(s): 2-5 (recommended ages 7-12)
* URL: [cognimates.me](https://cognimates.me)
* Creator: [Stefania Druga](https://www.media.mit.edu/people/sdruga/overview/), MIT Media Lab
* License: 

Description: Cognimates Scratch extensions provide capabilities such as speech recognition, sentiment recognition from text, and trainable visual object recognition (using Watson). The activity descriptions show how to use these extensions to create engaging demos. Children can also create their own AI models on the Teach AI section
![](https://github.com/touretzkyds/ai4k12/raw/master/images/cognimates.png)
@touretzkyds

**Comment by touretzkyds** [comment]
Thank you for the correction. It's live now.

**Comment by stefania11** [comment]
thank you!

**Comment by Mani0691** [comment]
Hello! I am trying to train some images through Cognimates - Train a vision model - When I upload the images I am getting an error stating " No data found for training". I am getting this error randomly, sometime it works alright. Some images get this error. Is there any specific reason?. 

Kindly help.
![Screenshot 2021-05-28 at 8 15 14 PM](https://user-images.githubusercontent.com/84979556/120001454-6e17a900-bff1-11eb-9e11-3f4223c52ce7.png)
