### ISSUE TITLE
Cognimates - Train a vision model - No data found for training

### ISSUE THREAD

**Issue by Mani0691** [touretzkyds/ai4k12#2]
When I try to upload images for training I get error that "No data found for training", I have created proper clarifai api, it happens randomly, some time the images gets trained and some time I am getting error. Kindly help me to fix this.
![Screenshot 2021-05-28 at 8 18 02 PM](https://user-images.githubusercontent.com/84979556/120001852-d797b780-bff1-11eb-8405-6d8f2094f1e4.png)

**Comment by touretzkyds** [comment]
This is not the right place to report issues with Cognimates. Please contact the developers directly: cognimates@gmail.com
